2024-01-10 04:58:06,911 - app - ERROR - Exception on /api/role [GET]
Traceback (most recent call last):
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/util.py", line 18, in wrapper
    raise e
  File "/Users/virender/Desktop/DriveKraft-Backend/app/util.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/authenticate.py", line 16, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/util.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/Routes/roleRoutes.py", line 15, in getRole
    response = roleService.getUserRole().__dict__
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/Services/roleService.py", line 8, in getUserRole
    user = userService.getUserDetails()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/Services/userService.py", line 98, in getUserDetails
    userid = g.userId
             ^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/ctx.py", line 54, in __getattr__
    raise AttributeError(name) from None
AttributeError: userId
2024-01-10 04:59:17,662 - app - ERROR - Exception on /api/role [GET]
Traceback (most recent call last):
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/util.py", line 18, in wrapper
    raise e
  File "/Users/virender/Desktop/DriveKraft-Backend/app/util.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/authenticate.py", line 16, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/util.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/Routes/roleRoutes.py", line 15, in getRole
    response = roleService.getUserRole().__dict__
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/Services/roleService.py", line 8, in getUserRole
    user = userService.getUserDetails()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virender/Desktop/DriveKraft-Backend/app/Services/userService.py", line 99, in getUserDetails
    user = getUserById(token.userId)
                       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'userId'
